services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: "${PGUSER}"
      POSTGRES_PASSWORD: "${PGPASSWORD}"
      POSTGRES_DB: "${PGDATABASE}"
    volumes:
      - db:/var/lib/postgresql
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER} -d ${PGDATABASE}"]
      interval: 5s
      retries: 10

  migrate:
    image: ghcr.io/ryansuhartanto/koda-b8-backendjs/tools:${BACKEND_TAG:-latest}
    build:
      context: backend
      target: tools
    environment:
      PGHOST: db
      PGUSER: "${PGUSER}"
      PGPASSWORD: "${PGPASSWORD}"
      PGDATABASE: "${PGDATABASE}"
    depends_on:
      db:
        condition: service_healthy
    restart: "no"

  api-go:
    image: ghcr.io/ryansuhartanto/koda-b8-backendjs/go:${BACKEND_TAG:-latest}
    build:
      context: backend
      target: go
    environment:
      PGHOST: db
      PGUSER: "${PGUSER}"
      PGPASSWORD: "${PGPASSWORD}"
      PGDATABASE: "${PGDATABASE}"
      JWT_SECRET: "${JWT_SECRET}"
      SQIDS_ALPHABET: "${SQIDS_ALPHABET}"
      GO_PORT: "${GO_PORT}"
    depends_on:
      migrate:
        condition: service_completed_successfully
    expose:
      - "${GO_PORT}"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q -O /dev/null http://localhost:${GO_PORT}/healthz",
        ]
      interval: 5s
      retries: 10

  api-js:
    image: ghcr.io/ryansuhartanto/koda-b8-backendjs/js:${BACKEND_TAG:-latest}
    build:
      context: backend
      target: js
    environment:
      PGHOST: db
      PGUSER: "${PGUSER}"
      PGPASSWORD: "${PGPASSWORD}"
      PGDATABASE: "${PGDATABASE}"
      JWT_SECRET: "${JWT_SECRET}"
      SQIDS_ALPHABET: "${SQIDS_ALPHABET}"
      JS_PORT: "${JS_PORT}"
    depends_on:
      migrate:
        condition: service_completed_successfully
    expose:
      - "${JS_PORT}"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q -O /dev/null http://localhost:${JS_PORT}/healthz",
        ]
      interval: 5s
      retries: 10

  api:
    image: load-balancer
    build: .
    environment:
      GO_PORT: "${GO_PORT}"
      JS_PORT: "${JS_PORT}"
      BACKEND_PORT: "${BACKEND_PORT}"
    depends_on:
      api-go:
        condition: service_healthy
      api-js:
        condition: service_healthy
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"

  web:
    image: ghcr.io/ryansuhartanto/koda-b8-react:${FRONTEND_TAG:-latest}
    build: frontend
    environment:
      VITE_BACKEND_URL: "http://localhost:${BACKEND_PORT}"
    depends_on:
      api:
        condition: service_started
    ports:
      - "${FRONTEND_PORT}:80"

volumes:
  db:
